dependencies:
  increment: ./target/wasm32-wasi/debug/increment.wasm
  show: ./target/wasm32-wasi/debug/show.wasm
  counter: ./target/wasm32-wasi/debug/count.wasm

instantiations:
  root:
    arguments:
      increment:increment/increase@0.1.0: increment
      shower:show/display@0.1.0: show
  increment:
    arguments:
      counter:count/change@0.1.0: counter
  show:
    arguments:
      counter:count/current@0.1.0: counter
